// Маппинг CoinGecko ID → Binance Symbol
export const coinIdToSymbol = {
    'bitcoin': 'BTC',
    'ethereum': 'ETH',
    'tether': 'USDT',
    'binancecoin': 'BNB',
    'solana': 'SOL',
    'ripple': 'XRP',
    'usd-coin': 'USDC',
    'cardano': 'ADA',
    'dogecoin': 'DOGE',
    'tron': 'TRX',
    'avalanche-2': 'AVAX',
    'shiba-inu': 'SHIB',
    'polkadot': 'DOT',
    'chainlink': 'LINK',
    'polygon': 'MATIC',
    'litecoin': 'LTC',
    'bitcoin-cash': 'BCH',
    'stellar': 'XLM',
    'uniswap': 'UNI',
    'ethereum-classic': 'ETC',
    'filecoin': 'FIL',
    'cosmos': 'ATOM',
    'hedera-hashgraph': 'HBAR',
    'arbitrum': 'ARB',
    'optimism': 'OP',
    'aptos': 'APT',
    'near': 'NEAR',
    'algorand': 'ALGO',
    'vechain': 'VET',
    'internet-computer': 'ICP',
    'aave': 'AAVE',
    'the-sandbox': 'SAND',
    'decentraland': 'MANA',
    'axie-infinity': 'AXS',
    'eos': 'EOS',
    'theta-token': 'THETA',
    'fantom': 'FTM',
    'flow': 'FLOW',
    'elrond-egd-2': 'EGLD',
    'tezos': 'XTZ',
    'pancakeswap-token': 'CAKE',
    'curve-dao-token': 'CRV',
    'maker': 'MKR',
    'zilliqa': 'ZIL',
    'enjincoin': 'ENJ',
    'compound-ether': 'COMP',
    'synthetix-network-token': 'SNX',
    'dash': 'DASH',
    'zcash': 'ZEC',
    'basic-attention-token': 'BAT',
    '1inch': '1INCH',
    'kava': 'KAVA',
    'gala': 'GALA',
    'render-token': 'RNDR',
    'injective-protocol': 'INJ',
    'sushi': 'SUSHI',
    'stacks': 'STX'
  }
  
  export function getSymbolFromId(coinId) {
    if (coinIdToSymbol[coinId]) {
      return coinIdToSymbol[coinId]
    }
    return coinId.toUpperCase().substring(0, 5)
  }